name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-deno-memory-store:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.36.4
    - name: Install dependencies
      working-directory: ./playwright
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./playwright
      run: npx playwright install chromium
    - name: Run Playwright tests
      working-directory: ./playwright
      run: npx playwright test

  test-deno-cookie-store:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      STORE: cookie
      ENCRYPTION_KEY: password_at_least_32_characters_long
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.36.4
    - name: Install dependencies
      working-directory: ./playwright
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./playwright
      run: npx playwright install chromium
    - name: Run Playwright tests
      working-directory: ./playwright
      run: npx playwright test

  test-deno-kv-store:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      STORE: kv
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.36.4
    - name: Install dependencies
      working-directory: ./playwright
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./playwright
      run: npx playwright install chromium
    - name: Run Playwright tests
      working-directory: ./playwright
      run: npx playwright test

  test-deno-sqlite-store:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      STORE: sqlite
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.36.4
    - name: Install dependencies
      working-directory: ./playwright
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./playwright
      run: npx playwright install chromium
    - name: Run Playwright tests
      working-directory: ./playwright
      run: npx playwright test

  test-bun-cookie-store:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      STORE: cookie
      JS_RUNTIME: bun
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.36.4
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.0.2
    - name: Install dependencies
      working-directory: ./playwright
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./playwright
      run: npx playwright install chromium
    - name: Build NPM package for library
      run: deno run -A scripts/build_npm.ts
    - name: Install bun example server
      working-directory: ./test/bun
      run: bun install
    - name: Run Playwright tests
      working-directory: ./playwright
      run: npx playwright test

  test-bun-sqlite-store:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      STORE: sqlite
      JS_RUNTIME: bun
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.36.4
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.0.2
    - name: Install dependencies
      working-directory: ./playwright
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./playwright
      run: npx playwright install chromium
    - name: Build NPM package for library
      run: deno run -A scripts/build_npm.ts
    - name: Install bun example server
      working-directory: ./test/bun
      run: bun install
    - name: Run Playwright tests
      working-directory: ./playwright
      run: npx playwright test

  test-cf-workers-cookie-store:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      JS_RUNTIME: cf_workers
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.36.4
    - name: Install dependencies
      working-directory: ./playwright
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./playwright
      run: npx playwright install chromium
    - name: Build NPM package for library
      run: deno run -A scripts/build_npm.ts
    - name: Install CF Workers example server
      working-directory: ./test/cloudflare_workers
      run: npm install
    - name: Run Playwright tests
      working-directory: ./playwright
      run: npx playwright test

  test-node-cookie-store:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      JS_RUNTIME: node
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.36.4
    - name: Install dependencies
      working-directory: ./playwright
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: ./playwright
      run: npx playwright install chromium
    - name: Build NPM package for library
      run: deno run -A scripts/build_npm.ts
    - name: Install node example server
      working-directory: ./test/node
      run: npm install
    - name: Run Playwright tests
      working-directory: ./playwright
      run: npx playwright test